### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by heiderich** [Saiyato/volumio-snapcast-plugin#37]
I tried to install the plugin on volumio 2.368-2018-02-18 as described in the REAME file, but got the following error:

```
volumio@volumio:~$ git clone https://github.com/Saiyato/volumio-snapcast-plugin
Cloning into 'volumio-snapcast-plugin'...
remote: Counting objects: 989, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 989 (delta 20), reused 24 (delta 13), pack-reused 949
Receiving objects: 100% (989/989), 17.33 MiB | 4.07 MiB/s, done.
Resolving deltas: 100% (394/394), done.
Checking connectivity... done.
volumio@volumio:~$ cd volumio-snapcast-plugin/
volumio@volumio:~/volumio-snapcast-plugin$ volumio plugin install

This command will install the plugin on your device


Compressing the plugin
Plugin succesfully compressed
/bin/mv: target ‘/tmp/plugins/snapcast.zip’ is not a directory
child_process.js:524
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/snapcast.zip
/bin/mv: target ‘/tmp/plugins/snapcast.zip’ is not a directory

    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at install (/volumio/pluginhelper.js:659:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:719:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

```

**Comment by jottgee** [comment]
I have the same problem.

**Comment by Saiyato** [comment]
It doesn't strike me as a problem in the plugin, but I will take a look

**Comment by Saiyato** [comment]
The latest instructions should solve this problem.

**Comment by heiderich** [comment]
Thanks.
