### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by miloit** [Saiyato/volumio-snapcast-plugin#48]
I do these steps:

volumio@volumio:~$ git clone https://github.com/Saiyato/volumio-snapcast-plugin.git
Cloning into 'volumio-snapcast-plugin'...
remote: Counting objects: 1061, done.
remote: Total 1061 (delta 0), reused 0 (delta 0), pack-reused 1061
Receiving objects: 100% (1061/1061), 16.97 MiB | 1.52 MiB/s, done.
Resolving deltas: 100% (446/446), done.
Checking connectivity... done.
volumio@volumio:~$ cd volumio-snapcast-plugin/
volumio@volumio:~/volumio-snapcast-plugin$ sudo rm volumio-snapcast-plugin.zip
volumio@volumio:~/volumio-snapcast-plugin$ sudo volumio plugin install

This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
/bin/rm: cannot remove 'package-lock.json': No such file or directory
Error installing node modules: Error: Command failed: /bin/rm package-lock.json
/bin/rm: cannot remove 'package-lock.json': No such file or directory

/bin/mv: cannot stat '*.zip': No such file or directory
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/snapcast.zip
/bin/mv: cannot stat '*.zip': No such file or directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at install (/volumio/pluginhelper.js:680:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:741:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

what is my error???

**Comment by Saiyato** [comment]
You are running the plug-in install as sudo.
